%% Import data from spreadsheet (DCE1)
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/yuyu/workspace/tobacco/Tobacco DCE1 data.xlsx
%    Worksheet: Data
%
% Auto-generated by MATLAB on 23-Jan-2020 20:45:29

%% Setup the Import Options and import the data

clear;
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = "Data";
opts.DataRange = "A2:L11326";

% Specify column names and types
opts.VariableNames = ["respid", "block", "WarningBgColor", "ImageSize", "set", "alt", "groupid", "att1image", "att2text", "most_likely", "least_likely", "setduration"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
TobaccoDCE1data = readtable("/Users/yuyu/workspace/tobacco/Tobacco DCE1 data.xlsx", opts, "UseExcel", false);

% Clear temporary variables
clear opts

%% change into dummies

att1image_index = find(strcmpi(TobaccoDCE1data.Properties.VariableNames,'att1image'));

att2text_index = find(strcmpi(TobaccoDCE1data.Properties.VariableNames,'att2text'));

dce1 = table2array(TobaccoDCE1data);

dce1(:,[att1image_index,att2text_index]) = categorical(dce1(:,[att1image_index,att2text_index]));


att1image_dummy = dummyvar(dce1(:,att1image_index));
att2text_dummy = dummyvar(dce1(:,att2text_index));

DCE1.data = [dce1,att1image_dummy,att2text_dummy];
DCE1.varNames = ["respid", "block", "WarningBgColor", "ImageSize", "set", "alt", "groupid", "att1image",...
    "att2text", "most_likely", "least_likely", "setduration","att1image_1",...
    "att1image_2","att1image_3","att1image_4","att1image_5","att1image_6",...
    "att1image_7","att1image_8","att1image_9","att2text_1","att2text_2"];
%%
save('DCE1_workingfile.mat','DCE1')

clear;
%%
%    Worksheet: Data
%
% Auto-generated by MATLAB on 23-Jan-2020 20:47:55

%% Setup the Import Options and import the data (DCE2)
opts = spreadsheetImportOptions("NumVariables", 16);

% Specify sheet and range
opts.Sheet = "Data";
opts.DataRange = "A2:P21141";

% Specify column names and types
opts.VariableNames = ["respid", "block", "WarningBgColor", "ImageSize", "block2", "DCE2image", "DCE2imagetxt", "set", "groupid", "alt", "attribute", "best", "secbest", "thirdbest", "worst", "setdur"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
TobaccoDCE2data = readtable("/Users/yuyu/workspace/tobacco/Tobacco DCE2 data.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts

%% turn into dummies
dce2 = table2array(TobaccoDCE2data);

DCE2image_index = find(strcmpi(TobaccoDCE2data.Properties.VariableNames,'DCE2image'));

DCE2imagetxt_index = find(strcmpi(TobaccoDCE2data.Properties.VariableNames,'DCE2imagetxt'));

dce2(:,[DCE2image_index,DCE2imagetxt_index]) = categorical(dce2(:,[DCE2image_index,DCE2imagetxt_index]));


DCE2image_dummy = dummyvar(dce2(:,DCE2image_index));
DCE2imagetxt_dummy = dummyvar(dce2(:,DCE2imagetxt_index));
%%
DCE2.data = [dce2,DCE2image_dummy,DCE2imagetxt_dummy];
DCE2.varNames = ["respid", "block", "WarningBgColor", "ImageSize", "block2",...
    "DCE2image", "DCE2imagetxt", "set", "groupid", "alt", "attribute", "best",...
    "secbest", "thirdbest", "worst", "setdur","DCE2image_1",...
    "DCE2image_2","DCE2image_3","DCE2image_4","DCE2image_5","DCE2image_6",...
    "DCE2image_7","DCE2image_8","DCE2image_9","DCE2imagetxt_1","DCE2imagetxt_2"];

save('DCE2_workingfile.mat','DCE2')

clear;